### ISSUE TITLE
Error if installing or update in Contao 4.9.x

### ISSUE THREAD

**Issue by MacKP** [markocupic/export_table#12]
Version 5.3.12 of export_table is working fine. The new Version after that has an error on install:
`Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception`

```
PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /project/vendor/markocupic/export_table/src/Config/Config.php on line 62
```

I think the change was during the compatibility fix for contao 5.0.

Kind regards

**Comment by markocupic** [comment]
Sorry, I forgot to remove php 7.4 dependency from composer.json. Remove and then reinstall the application should solve the issue.

Version 5.4.x requires php 8.1.

**Comment by MacKP** [comment]
Ah, thats the case here.
Sadly reinstalling doesn't work for me. In my composer.lock export_table is listed as:
`"version": "5.3.15",`
But the Error is still existing.

**Comment by markocupic** [comment]
In the require key of your composer.json you could try "markocupic/export_table": "^5.3 || < 5.4"

**Comment by MacKP** [comment]
That doesn't work neither. I need to call the specific Version 5.3.12.
Everything after that has this Error.

**Comment by markocupic** [comment]
Same error?

> `PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /project/vendor/markocupic/export_table/src/Config/Config.php on line 62`

**Comment by MacKP** [comment]
Yes. Still the same.

**Comment by markocupic** [comment]
Could you post Line 62 of project/vendor/markocupic/export_table/src/Config/Config.php?

**Comment by MacKP** [comment]
With:
`"markocupic/export_table": "^5.3 || < 5.4",`
Version 5.3.15 is installed.
Line 62 of  project/vendor/markocupic/export_table/src/Config/Config.php:
`public function getModel(): ExportTableModel|null`
Kind regards

**Comment by markocupic** [comment]
- Download version [5.3.12](https://github.com/markocupic/export_table/archive/refs/tags/5.3.12.zip) manually and override the existing version.
- In your composer.json you write: `"markocupic/export_table": "5.3.12"`
- The run `composer install`

**Comment by MacKP** [comment]
Yes, this is working (as i told you...). The Problem is the requirement. Everyone with the /calendar-event-booking-bundle and not php8.1 will have this Problem.
Kind regards

**Comment by markocupic** [comment]
> The Problem is the requirement. Everyone with the /calendar-event-booking-bundle and not php8.1 will have this Problem.
No, I don't think. I've deleted version the invalid versions 5.3.13 up to 5.3.15 from packagist.org. 
The new version 5.4.0 has a php minimum requirement of ^8.1.

**Comment by MacKP** [comment]
Nice, now this works.
Kind regards
